"""
api/chatbot.py - AI Chatbot Interface.
This module facilitates real-time interaction with a local LLM (phi3 via Ollama) 
to assist users with application-specific questions, navigation, and role-based 
capability summaries. It implements strict context-aware prompt engineering to 
ensure security and relevance.
"""

from fastapi import APIRouter, HTTPException, Header, Request
from pydantic import BaseModel, Field
import httpx
import logging
import os
from slowapi import Limiter
from slowapi.util import get_remote_address
from typing import Any, Dict, Optional

router = APIRouter()
logger = logging.getLogger(__name__)
limiter = Limiter(key_func=get_remote_address)

# External LLM service configuration
OLLAMA_URL = os.getenv("OLLAMA_HOST")

# ============================================================
# MODELS
# ============================================================

class ChatRequest(BaseModel):
    """
    Data model for a chatbot query.
    
    Attributes:
        query (str): The natural language question from the user.
        context (Optional[Dict[str, Any]]): Metadata including role, username, and current page.
    """
    query: str
    context: Optional[Dict[str, Any]] = Field(default_factory=dict)

class ChatResponse(BaseModel):
    """
    Data model for the chatbot's generated answer.
    
    Attributes:
        response (str): The text generated by the AI.
        model (str): Identifier of the LLM used (e.g., 'phi3').
        context_used (bool): Whether role-based context was applied to the prompt.
    """
    response: str
    model: str
    context_used: bool


# ============================================================
# CONFIGURATION & UTILITIES
# ============================================================

# Concise per-role access summary - used to guide the AI's understanding of user permissions
ROLE_ACCESS = {
    'ADMIN': (
        "Tasks: create, assign, approve, delete any task.\n"
        "Employees: add, edit, remove, assign to teams.\n"
        "Teams & Departments: create and manage all.\n"
        "AI: assignment suggestions, duration predictions, anomaly detection.\n"
        "Analytics: full productivity and workload reports.\n"
        "Users: manage accounts and roles.\n"
        "Cannot do: nothing - full access."
    ),
    'MANAGER': (
        "Tasks: create, assign, approve/reject tasks for your teams.\n"
        "Employees: view profiles in your teams.\n"
        "Teams: manage your own teams.\n"
        "AI: assignment suggestions, workload monitoring.\n"
        "Analytics: team-level reports only.\n"
        "Cannot do: manage users, change system settings, see other teams' data."
    ),
    'EMPLOYEE': (
        "Tasks: view, accept, start, complete your assigned tasks.\n"
        "Requests: submit task requests (need manager approval).\n"
        "Profile: update your own skills and info.\n"
        "Chat: message your team.\n"
        "Cannot do: create tasks, view other employees' data, access AI tools or analytics."
    ),
    'USER': (
        "You have a basic account with no employee profile yet.\n"
        "Available: view dashboard, check notifications.\n"
        "Cannot do: almost everything - contact your Admin to create your employee profile first."
    )
}

# Heuristic phrases to detect meta-questions about application capabilities
CAPABILITY_PHRASES = [
    'what can i do', 'what do i have', 'what features', 'what is available',
    'show me what', 'guide me', 'what are my options', 'capabilities',
    'what can the app', 'what does this app', 'overview', 'summarize',
    'explain the app', 'how does this work', 'tell me what', 'what access',
    'help me', 'how do i', 'where can i', 'show me how',
    'navigate to', 'find the', 'how to use', 'tutorial',
    'what should i', 'getting started', 'instructions'
]

# Detailed app feature knowledge for contextual assistance
APP_FEATURES = {
    'tasks': (
        "Tasks page: Create, assign, and track tasks through their lifecycle. "
        "Use status filters (PENDING, IN_PROGRESS, COMPLETED, BLOCKED, CANCELLED). "
        "Employees can submit task requests that need manager/admin approval. "
        "Click a task to see details, comments, time logs, and audit history."
    ),
    'assignments': (
        "AI Assignment: Open a task → click 'Get AI Suggestions'. "
        "The AI ranks employees by skill match (40%), workload capacity (25%), "
        "experience alignment (15%), adaptability (10%), and priority fit (10%). "
        "Each suggestion includes a fit score, confidence, and detailed reasoning."
    ),
    'analytics': (
        "Analytics page: View team productivity metrics including completion rates, "
        "on-time delivery percentage, average task duration, and skill utilization. "
        "Use the 'Bust Cache' button to force-refresh data. "
        "Available to ADMIN and MANAGER roles only."
    ),
    'workload': (
        "Workload page: See employee utilization levels. "
        "UNDERLOADED = below 50%%, OPTIMAL = 50-85%%, OVERLOADED = above 85%%. "
        "Filter by status to find available team members for new assignments."
    ),
    'teams': (
        "Teams page: Create teams, add or remove members. "
        "Each team has a shared chat channel. "
        "Team-based task assignments notify all team members."
    ),
    'chat': (
        "Chat: Direct messages between employees and team group chats. "
        "Real-time messaging via WebSocket. "
        "Unread message counts shown in the navigation badge."
    ),
    'predictions': (
        "AI Predictions: Get duration estimates for tasks based on complexity, "
        "priority, required skills, and historical completion data. "
        "Includes confidence intervals showing the estimated range."
    ),
    'skills': (
        "Skills: AI extracts skills from task descriptions automatically. "
        "Employees manage their own skill profiles with proficiency levels (1-5). "
        "Skills are matched during AI assignment to find the best fit."
    ),
    'employees': (
        "Employees page: View all employee profiles, their departments, "
        "positions, skills, and workload. Admin can create new employee profiles "
        "for existing users, which promotes them from USER to EMPLOYEE role."
    ),
    'departments': (
        "Departments page: Organize employees into departments like Engineering, "
        "Marketing, Sales. Admin can create and delete departments."
    ),
    'notifications': (
        "Notifications: Real-time alerts for task assignments, status changes, "
        "approvals, rejections, team updates, and deadline reminders. "
        "Click the bell icon to view and mark notifications as read."
    ),
    'dashboard': (
        "Dashboard: Overview of your tasks, recent activity, and key metrics. "
        "Quick access to pending items and notifications."
    ),
}


def build_prompt(role: str, username: str, page: str, query: str) -> str:
    """
    Constructs a context-rich prompt for the LLM based on user metadata.
    Implements few-shot instruction to enforce brevity and role-appropriate advice.
    
    Args:
        role (str): The user's authorization role.
        username (str): The user's display name.
        page (str): The current UI location.
        query (str): The user's original query.
        
    Returns:
        str: A formatted prompt string ready for inference.
    """
    access = ROLE_ACCESS.get(role, ROLE_ACCESS['USER'])
    query_lower = query.lower()
    is_capability_q = any(p in query_lower for p in CAPABILITY_PHRASES)

    if is_capability_q:
        # Specialized prompt for capability discovery
        return (
            f"You are a helpful assistant. The user is {username}, role: {role}.\n"
            f"Their access:\n{access}\n\n"
            f"List what {username} can do in this app using the access above. "
            f"Use short bullet points grouped by section. "
            f"End with 1 line on what they cannot do. "
            f"Max 120 words. No marketing language.\n\n"
            f"Question: {query}\nAnswer:"
        )
    else:
        # Build page-specific context hint
        page_lower = page.lower() if page else ''
        page_tip = ''
        for feature_key, feature_desc in APP_FEATURES.items():
            if feature_key in page_lower or feature_key in query_lower:
                page_tip = f"\nRelevant feature info: {feature_desc}\n"
                break

        # Standard assistance prompt
        return (
            f"You are a helpful assistant for the Smart Resource Planner app. "
            f"User: {username}, role: {role}, page: {page}.\n"
            f"Their access summary: {access}\n"
            f"{page_tip}\n"
            f"Answer this question in plain English, max 80 words. "
            f"If they ask about something they cannot do, say so and tell them who to contact. "
            f"If they ask how to do something, give specific step-by-step instructions. "
            f"No marketing language. Use 'you can' not 'we'.\n\n"
            f"Question: {query}\nAnswer:"
        )


# ============================================================
# ENDPOINTS
# ============================================================

@router.post("/query", response_model=ChatResponse)
@limiter.limit("15/minute")
async def query_chatbot(
    request: Request,
    chat_request: ChatRequest,
    x_company_id: Optional[str] = Header(None),
    authorization: Optional[str] = Header(None)
):
    """
    Handles user queries by proxying them to the local Ollama LLM.
    Wraps the raw query in a persona-driven prompt to ensure system-accurate answers.
    
    Args:
        request (ChatRequest): The query and context data.
        x_company_id (Optional[str]): Company ID.
        authorization (Optional[str]): Auth token.
        
    Returns:
        ChatResponse: The AI-generated answer.
    """
    try:
        # Extract context variables for prompt tailoring
        role = chat_request.context.get('role', 'USER')
        page = chat_request.context.get('page', 'dashboard')
        username = chat_request.context.get('username', 'there')

        prompt = build_prompt(role, username, page, chat_request.query)

        # Configure Ollama parameters for reproducible, fast responses
        ollama_payload = {
            "model": "phi3",
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.5,
                "top_p": 0.9,
                "top_k": 40,
                "num_predict": 200,  # Limits generation length to prevent latency spikes
                "num_ctx": 1024      # Optimized context window for small local models
            }
        }

        try:
            # Asynchronous call to Ollama within a timeout window
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{OLLAMA_URL}/api/generate",
                    json=ollama_payload,
                    timeout=28.0  # Ensures we respond before the proxy/gateway times out
                )
            response.raise_for_status()

        except httpx.ConnectError:
            return ChatResponse(
                response="Cannot connect to the AI service. Please check with your administrator.",
                model="phi3", context_used=False
            )
        except httpx.TimeoutException:
            return ChatResponse(
                response="The AI took too long to respond. Try asking a shorter question.",
                model="phi3", context_used=False
            )

        if response.status_code == 200:
            try:
                data = response.json()
                assistant_response = data.get("response", "").strip()

                if not assistant_response:
                    return ChatResponse(
                        response="No response generated. Please rephrase your question.",
                        model="phi3", context_used=False
                    )

                return ChatResponse(response=assistant_response, model="phi3", context_used=True)
            except ValueError:
                return ChatResponse(
                    response="Received a malformed response from the AI engine.",
                    model="phi3", context_used=False
                )
        else:
            return ChatResponse(
                response=f"AI service error: {response.status_code}. Please try again later.",
                model="phi3", context_used=False
            )

    except Exception as e:
        logger.error(f"Chatbot controller failure: {str(e)}")
        return ChatResponse(
            response="An unexpected exception occurred while processing your request.",
            model="phi3", context_used=False
        )


@router.get("/health")
async def chatbot_health():
    """
    Performs a health check on the underlying Ollama service and model availability.
    Checks for the presence of the 'phi3' model.
    
    Returns:
        dict: Health status and metadata about available models.
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(f"{OLLAMA_URL}/api/tags", timeout=5.0)

        if response.status_code == 200:
            data = response.json()
            models = data.get("models", [])
            model_names = [m.get("name") for m in models]
            has_phi3 = any("phi3" in name for name in model_names)

            if not has_phi3:
                return {
                    "status": "degraded",
                    "message": "Ollama is active but the required 'phi3' model is missing",
                    "ollama_url": OLLAMA_URL,
                    "available_models": model_names
                }

            return {
                "status": "healthy",
                "ollama_url": OLLAMA_URL,
                "available_models": model_names,
                "using_model": "phi3"
            }
        else:
            return {
                "status": "unhealthy",
                "error": f"Ollama heartbeat failed with status {response.status_code}",
                "ollama_url": OLLAMA_URL
            }

    except httpx.TimeoutException:
        return {"status": "checking", "message": "Ollama service is starting up...", "ollama_url": OLLAMA_URL}
    except httpx.ConnectError:
        return {"status": "unhealthy", "error": "Unable to connect to Ollama", "ollama_url": OLLAMA_URL}
    except Exception as e:
        return {"status": "error", "error": str(e), "ollama_url": OLLAMA_URL}


@router.post("/pull-model")
async def pull_model(model_name: str = "phi3"):
    """
    Instructs the LLM service to download/pull a specific model.
    Only use this if 'health' returns a missing model status.
    
    Args:
        model_name (str): The model identifier to pull.
        
    Returns:
        dict: Success message if the pull initiated.
        
    Raises:
        HTTPException: On various connectivity or service errors.
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{OLLAMA_URL}/api/pull",
                json={"name": model_name},
                timeout=600.0  # Extended timeout for model downloads
            )

        if response.status_code == 200:
            return {"status": "success", "message": f"Successfully initiated pull for '{model_name}'"}
        else:
            raise HTTPException(status_code=response.status_code, detail=f"Ollama failed to pull model: {response.text}")

    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail=f"Operation timed out while pulling '{model_name}'")
    except httpx.ConnectError:
        raise HTTPException(status_code=503, detail="AI Service is unreachable")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Unexpected error: {str(e)}")