sonar.projectKey=thesis-frontend
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_4d0feaad643d0a4b24fba32f8903bbd0eadeb79a
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/vite-env.d.ts,src/main.tsx,src/main.jsx,src/test/**/*,src/test/setupTests.ts,src/__tests__/**/*,src/test/testUtils.tsx
sonar.typescript.tsconfigPath=tsconfig.sonar.json
