# ai_service/app/models/constraint_solver.py
"""
Constraint Programming for Optimal Team Workload Balancing
Uses OR-Tools CP-SAT solver for provably optimal assignments
"""

import logging
from typing import List, Dict
from dataclasses import dataclass

try:
    from ortools.sat.python import cp_model
    ORTOOLS_AVAILABLE = True
except ImportError:
    ORTOOLS_AVAILABLE = False
    logging.warning("OR-Tools not available - constraint solver disabled")

logger = logging.getLogger(__name__)


@dataclass
class Task:
    """
    Represents a task requiring assignment.
    Holds required priority, complexity, skills, and estimated hours.
    """
    id: str
    priority: int  # 1-4
    complexity: float
    required_skills: List[str]
    estimated_hours: float


@dataclass
class Employee:
    """
    Represents an employee available for tasks.
    Contains skill proficiencies and workload capacity constraints.
    """
    id: str
    name: str
    skills: Dict[str, int]  # {skill_id: proficiency}
    max_hours: int
    current_workload: float


@dataclass
class Assignment:
    """
    Represents an optimal task assignment generated by the solver.
    Includes fit scores and reasoning for the match.
    """
    task_id: str
    employee_id: str
    employee_name: str
    fit_score: float
    reasoning: str


class WorkloadBalancingSolver:
    """
    CP-SAT solver for optimal task assignment
    
    Objectives:
    1. Maximize skill match (primary)
    2. Minimize workload imbalance (secondary)
    3. Respect capacity constraints (hard)
    """
    
    def __init__(self):
        if not ORTOOLS_AVAILABLE:
            raise RuntimeError("OR-Tools required")
        
        self.model = None
        self.solver = None
    
    def solve(
        self,
        tasks: List[Task],
        employees: List[Employee],
        weights: Dict[str, float] = None
    ) -> List[Assignment]:
        """
        Find optimal assignment balancing skills and workload
        """
        
        if weights is None:
            # Default objective weights if none are provided
            weights = {
                'skill_match': 0.5,
                'workload_balance': 0.3,
                'priority': 0.2
            }
                
        self.model = cp_model.CpModel()
        
        # Decision variables
        # Map (task_index, emp_index) to a boolean variable

        assignments = {}
        for i, task in enumerate(tasks):
            for j, emp in enumerate(employees):
                assignments[(i, j)] = self.model.NewBoolVar(f'assign_t{i}_e{j}')
        
        # CONSTRAINT 1: Each task assigned to exactly one employee
        for i in range(len(tasks)):
            self.model.Add(sum(assignments[(i, j)] for j in range(len(employees))) == 1)
        
        # CONSTRAINT 2: Employee workload ≤ max_hours
        for j, emp in enumerate(employees):
            total_hours = sum(
                assignments[(i, j)] * int(tasks[i].estimated_hours)
                for i in range(len(tasks))
            )
            available = emp.max_hours - int(emp.current_workload)
            self.model.Add(total_hours <= available)
        
        # OBJECTIVE: Weighted combination
        objective_terms = []
        
        # 1. Skill match quality
        for i, task in enumerate(tasks):
            for j, emp in enumerate(employees):
                fit_score = self._calculate_fit_score(task, emp)
                score_int = int(fit_score * 1000)
                objective_terms.append(
                    assignments[(i, j)] * score_int * int(weights['skill_match'] * 100)
                )
        
        # 2. Workload balance
        workloads = []
        for j, emp in enumerate(employees):
            workload_var = self.model.NewIntVar(0, emp.max_hours, f'workload_e{j}')
            self.model.Add(
                workload_var == sum(
                    assignments[(i, j)] * int(tasks[i].estimated_hours)
                    for i in range(len(tasks))
                ) + int(emp.current_workload)
            )
            workloads.append(workload_var)
        
        # Minimize deviation from average
        avg_workload = int(
            (sum(e.current_workload for e in employees) + 
             sum(t.estimated_hours for t in tasks)) / len(employees)
        )
        
        for wl in workloads:
            deviation = self.model.NewIntVar(0, 1000, 'deviation')
            self.model.AddAbsEquality(deviation, wl - avg_workload)
            objective_terms.append(-deviation * int(weights['workload_balance'] * 10))
        
        # 3. Priority
        for i, task in enumerate(tasks):
            for j in range(len(employees)):
                priority_bonus = task.priority * 10
                objective_terms.append(
                    assignments[(i, j)] * priority_bonus * int(weights['priority'] * 100)
                )
        
        self.model.Maximize(sum(objective_terms))
        
        # Solve
        self.solver = cp_model.CpSolver()
        self.solver.parameters.max_time_in_seconds = 30.0
        
        status = self.solver.Solve(self.model)
        
        results = []
        if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:            
            for i, task in enumerate(tasks):
                for j, emp in enumerate(employees):
                    if self.solver.Value(assignments[(i, j)]) == 1:
                        fit_score = self._calculate_fit_score(task, emp)
                        results.append(Assignment(
                            task_id=task.id,
                            employee_id=emp.id,
                            employee_name=emp.name,
                            fit_score=fit_score,
                            reasoning=self._generate_reasoning(task, emp, fit_score)
                        ))
                        break
            
        else:
            logger.error(f"No solution ({self.solver.StatusName(status)})")
        
        return results
    
    def _calculate_fit_score(self, task: Task, employee: Employee) -> float:
        """Calculate skill match score"""
        if not task.required_skills:
            return 0.5
        
        matched = 0
        total_prof = 0
        
        for skill_id in task.required_skills:
            if skill_id in employee.skills:
                matched += 1
                total_prof += employee.skills[skill_id] / 5.0
        
        if matched == 0:
            return 0.0
        
        coverage = matched / len(task.required_skills)
        quality = total_prof / matched
        
        fit_score = (coverage * 0.7) + (quality * 0.3)
        
        if task.complexity > 0.7 and quality > 0.8:
            fit_score *= 1.1
        
        return min(fit_score, 1.0)
    
    def _generate_reasoning(self, task: Task, emp: Employee, fit: float) -> str:
        """Generate explanation"""
        if not task.required_skills:
            return f"Optimal workload assignment for {emp.name}"
        
        matched = sum(1 for s in task.required_skills if s in emp.skills)
        
        reasons = []
        if matched == len(task.required_skills):
            reasons.append(f"Has all {len(task.required_skills)} required skills")
        elif matched > 0:
            reasons.append(f"Has {matched}/{len(task.required_skills)} required skills")
        else:
            reasons.append("Will need training")
        
        util = (emp.current_workload / emp.max_hours) * 100
        if util < 50:
            reasons.append("Good availability")
        elif util < 85:
            reasons.append("Optimal workload")
        else:
            reasons.append("Near capacity")
        
        if fit >= 0.8:
            reasons.append("Excellent match")
        elif fit >= 0.6:
            reasons.append("Good match")
        else:
            reasons.append("Acceptable with balance")
        
        return " • ".join(reasons)
    
    def get_stats(self) -> Dict:
        """Get solution statistics"""
        if self.solver is None:
            return {}
        
        return {
            'objective_value': self.solver.ObjectiveValue(),
            'solve_time_seconds': self.solver.WallTime(),
            'num_conflicts': self.solver.NumConflicts(),
            'num_branches': self.solver.NumBranches()
        }


def solve_optimal_assignments(
    tasks_data: List[Dict],
    employees_data: List[Dict],
    weights: Dict[str, float] = None
) -> List[Dict]:
    """
    High-level function for optimal assignments
    """
    
    if not ORTOOLS_AVAILABLE:
        logger.error("OR-Tools not available")
        return _greedy_fallback(tasks_data, employees_data)
    
    # Convert to solver format
    tasks = [
        Task(
            id=t['id'],
            priority={'LOW': 1, 'MEDIUM': 2, 'HIGH': 3, 'CRITICAL': 4}.get(t.get('priority', 'MEDIUM'), 2),
            complexity=t.get('complexityScore', 0.5),
            required_skills=t.get('requiredSkillIds', []),
            estimated_hours=t.get('estimatedHours', 8.0)
        )
        for t in tasks_data
    ]
    
    employees = [
        Employee(
            id=e['id'],
            name=f"{e.get('first_name', '')} {e.get('last_name', '')}",
            skills=e.get('skills', {}),
            max_hours=e.get('max_weekly_hours', 40),
            current_workload=e.get('active_tasks', 0) * 8.0
        )
        for e in employees_data
    ]
    
    solver = WorkloadBalancingSolver()
    assignments = solver.solve(tasks, employees, weights)
    
    results = [
        {
            'task_id': a.task_id,
            'employee_id': a.employee_id,
            'employee_name': a.employee_name,
            'fit_score': a.fit_score,
            'reasoning': a.reasoning,
            'optimization_method': 'constraint_programming'
        }
        for a in assignments
    ]
    
    stats = solver.get_stats()
    
    return results


def _greedy_fallback(tasks_data: List[Dict], employees_data: List[Dict]) -> List[Dict]:
    """Fallback greedy assignment"""
    results = []
    for task in tasks_data:
        best_emp = None
        best_score = -1
        
        for emp in employees_data:
            score = 0.5
            task_skills = task.get('requiredSkillIds', [])
            emp_skills = emp.get('skills', {})
            
            if task_skills:
                matched = sum(1 for s in task_skills if s in emp_skills)
                score = matched / len(task_skills)
            
            workload = emp.get('active_tasks', 0) * 8
            max_hours = emp.get('max_weekly_hours', 40)
            
            if workload < max_hours * 0.8:
                score *= 1.2
            
            if score > best_score:
                best_score = score
                best_emp = emp
        
        if best_emp:
            results.append({
                'task_id': task['id'],
                'employee_id': best_emp['id'],
                'employee_name': f"{best_emp.get('first_name', '')} {best_emp.get('last_name', '')}",
                'fit_score': best_score,
                'reasoning': 'Greedy fallback',
                'optimization_method': 'greedy'
            })
    
    return results